### ISSUE TITLE
Add readme with setup guide

### ISSUE THREAD

**Issue by kaplanan** [chrko/mb-exporter#1]
Add a readme (`adoc` or `md`) with explanatory 'Getting started' section. That is, where (developer.m**-b**.com) to request which products ('Fuel Status' etc.)

**Comment by chrko** [comment]
Basic readme defined in https://github.com/chrko/mb-exporter/commit/890eed8e6990a972b51b559062b0baa3187b709c. Feel free to extend the instructions.
